# Generated by Django 2.2.5 on 2019-09-27 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20190926_0650'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
