# Generated by Django 2.2.5 on 2019-09-27 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_delete_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='being_received',
        ),
        migrations.RemoveField(
            model_name='order',
            name='received',
        ),
    ]
