# Generated by Django 2.2.5 on 2019-09-27 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20190927_1031'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
