# Generated by Django 2.2.5 on 2019-09-30 10:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_item_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
