# Generated by Django 2.2.5 on 2019-09-30 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20190930_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='created_on',
        ),
    ]
