# Generated by Django 2.2.5 on 2019-10-03 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_order_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('S', 'Shirt'), ('SW', 'Sport wear'), ('OW', 'Outwear'), ('CL', 'Classy'), ('EW', 'Ethnic Wear'), ('WW', 'Western Wear'), ('FW', 'Fusion Wear'), ('FOW', 'Formal Wear'), ('LJ', 'Leggings & Jeggings')], max_length=2),
        ),
    ]
